import { useMemo } from 'react';
import { BrainCircuit } from 'lucide-react';

interface AISummaryTabProps {
  summary: string;
}

export default function AISummaryTab({ summary }: AISummaryTabProps) {
  const sections = useMemo(() => {
    const parts = summary.split(/^## /).filter(Boolean);
    return parts.map((part) => {
      const lines = part.split('\n');
      const title = lines[0].trim();
      const body = lines.slice(1).join('\n').trim();
      return { title, body };
    });
  }, [summary]);

  return (
    <div className="h-full overflow-y-auto scrollbar-thin p-5">
      <div className="flex items-center gap-2 mb-4">
        <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-cyan-500/20 to-teal-500/10 border border-cyan-400/30 flex items-center justify-center">
          <BrainCircuit className="w-4 h-4 text-cyan-300" />
        </div>
        <div>
          <h3 className="text-sm font-semibold text-slate-200">Scientific AI Summary</h3>
          <p className="text-[10px] font-mono text-slate-500 uppercase tracking-wider">
            Generated by FloatChat Oceanographic LLM
          </p>
        </div>
      </div>

      <div className="space-y-4">
        {sections.map((section, i) => (
          <div
            key={i}
            className="glass rounded-xl border border-cyan-500/10 p-4 animate-fade-in"
            style={{ animationDelay: `${i * 100}ms` }}
          >
            <h4 className="text-sm font-semibold text-cyan-300 mb-2">{section.title}</h4>
            <div className="text-sm text-slate-300 leading-relaxed space-y-1.5">
              {section.body.split('\n').map((line, j) => {
                if (!line.trim()) return null;
                const formatted = line.replace(/\*\*(.+?)\*\*/g, '<strong class="text-cyan-200">$1</strong>');
                return (
                  <p
                    key={j}
                    className={line.startsWith('###') ? 'text-xs font-semibold text-teal-300 mt-2 mb-1' : ''}
                    dangerouslySetInnerHTML={{ __html: formatted.replace(/^###\s*/, '') }}
                  />
                );
              })}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
